### ISSUE TITLE
TODO list for new theme 20190413

### ISSUE THREAD

**Issue by karuto** [karuto/karu-theme#2]
## Header & footer
- [x] Separate head from header, so header would be just the top nav.
- [x] Move header into `header` subfolder in `template-parts`.
- [x] Move footer into `footer` subfolder in `template-parts`.
- [ ] Understand the support for WordPress menus. Try not to hard code it this time.
- [x] Understand `wp_header` and `wp_footer`.
## Archive & content
- [x] Create a template file just to handle the heading (`page-header`); make all templates use this.
- [x] Create a `feeds` template to handle the while have posts logic; this is duplicated in archive, home, page and single. Personally I think what we have in `vincentzh-theme` is pretty good level of abstraction.
- [x] Create a `content` template to handle the shared parts of page and single.
- [x] Consider renaming single to post, since it only handles posts not other single types (pages, attachements).
## CSS
- [x] Migrate CSS from `vincentzh-theme`.

**Comment by karuto** [comment]
20190414 - everything except the accommodation of menus is completed. I'll migrate that item to a new ticket. Closing this one.
