### ISSUE TITLE
TODO 20190414

### ISSUE THREAD

**Issue by karuto** [karuto/karu-theme#3]
Now that the majority of CSS is migrated over, it's time to consider the next steps.

What is my MVP? The goal is to create an opinionated but generic enough template system for all my future theming needs. If that's the case, the following items must be completed:

- [x] Lay out a plan of the potential type of themes I'm going to need, define the scope of this project (how opinionated / generic) would you like it to be?
- [x] Test a child theme in action.
- [x] Do we need to change any `get_template_part` formats?

Now that I've replaced most of the CSS and a large portion of the templates with my own from `vincentzh-theme`, I lost a lot of the flexibilities of the original Twentynineteen, for example, the support of thumbnails in posts. I suggest to go through the supported features of Twentynineteen and make a wish list of features I've deleted but would like to support (perhaps in a more personal / elegant way) in future.

**Comment by karuto** [comment]
Do the wishlist thing in a separate issue. Closing this one as I've figured out how to implement child themes.
